framework:
    asset_mapper:
        paths:
            - assets/
        excluded_patterns:
            - '*/vendor/*'
            - '*/node_modules/*'
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            enabled: true
            missing_import_mode: warn
